apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.lvm.name }}
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  volumeType: "LVM"
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.lvm_xfs.name }}
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  volumeType: "LVM"
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.device_hdd.name }}
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  csi.storage.k8s.io/fstype: ext4
  volumeType: Device
  mediaType: hdd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.device_ssd.name }}
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  csi.storage.k8s.io/fstype: ext4
  volumeType: Device
  mediaType: ssd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.lvm_throttle.name }}
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  volumeType: "LVM"
  bps: "1048576"
  iops: "1024"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.hostpath.name }}-legacy
  annotations:
    local.csi.aliyun.com/config: |
      - name: BasePath
        value: /var/open-local/local
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}/hostpath
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
# TODO(x.zhou): allow volume expansion
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.hostpath.name }}-legacy-quota
  annotations:
    local.csi.aliyun.com/config: |
      - name: BasePath
        value: /var/open-local/local
      - name: EXT4Quota
        enabled: true
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}/hostpath
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
# TODO(x.zhou): allow volume expansion
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.hostpath.name }}
  annotations:
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  volumeType: "HostPath"
  hostPath: "/mnt/{{ .Values.name }}/hostpathpvs"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.hostpath.name }}-quota
  annotations:
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  volumeType: "HostPath"
  hostPath: "/mnt/{{ .Values.name }}/hostpathpvs"
  enforceCapacityLimit: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.storageclass.lvm.name }}
{{ include "local.labels" . | indent 2 }}
driver: {{ .Values.driver }}
deletionPolicy: Delete
parameters:
  csi.aliyun.com/readonly: "true"
  csi.aliyun.com/snapshot-initial-size: 4Gi
  csi.aliyun.com/snapshot-expansion-size: 1Gi
  csi.aliyun.com/snapshot-expansion-threshold: 50%
