// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: lvm.proto

package lib

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LVM_ListLV_FullMethodName         = "/proto.LVM/ListLV"
	LVM_CreateLV_FullMethodName       = "/proto.LVM/CreateLV"
	LVM_RemoveLV_FullMethodName       = "/proto.LVM/RemoveLV"
	LVM_CloneLV_FullMethodName        = "/proto.LVM/CloneLV"
	LVM_ExpandLV_FullMethodName       = "/proto.LVM/ExpandLV"
	LVM_CreateSnapshot_FullMethodName = "/proto.LVM/CreateSnapshot"
	LVM_RemoveSnapshot_FullMethodName = "/proto.LVM/RemoveSnapshot"
	LVM_AddTagLV_FullMethodName       = "/proto.LVM/AddTagLV"
	LVM_RemoveTagLV_FullMethodName    = "/proto.LVM/RemoveTagLV"
	LVM_ListVG_FullMethodName         = "/proto.LVM/ListVG"
	LVM_CreateVG_FullMethodName       = "/proto.LVM/CreateVG"
	LVM_RemoveVG_FullMethodName       = "/proto.LVM/RemoveVG"
	LVM_CleanPath_FullMethodName      = "/proto.LVM/CleanPath"
	LVM_CleanDevice_FullMethodName    = "/proto.LVM/CleanDevice"
	LVM_DoCommand_FullMethodName      = "/proto.LVM/DoCommand"
)

// LVMClient is the client API for LVM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LVMClient interface {
	ListLV(ctx context.Context, in *ListLVRequest, opts ...grpc.CallOption) (*ListLVReply, error)
	CreateLV(ctx context.Context, in *CreateLVRequest, opts ...grpc.CallOption) (*CreateLVReply, error)
	RemoveLV(ctx context.Context, in *RemoveLVRequest, opts ...grpc.CallOption) (*RemoveLVReply, error)
	CloneLV(ctx context.Context, in *CloneLVRequest, opts ...grpc.CallOption) (*CloneLVReply, error)
	ExpandLV(ctx context.Context, in *ExpandLVRequest, opts ...grpc.CallOption) (*ExpandLVReply, error)
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotReply, error)
	RemoveSnapshot(ctx context.Context, in *RemoveSnapshotRequest, opts ...grpc.CallOption) (*RemoveSnapshotReply, error)
	AddTagLV(ctx context.Context, in *AddTagLVRequest, opts ...grpc.CallOption) (*AddTagLVReply, error)
	RemoveTagLV(ctx context.Context, in *RemoveTagLVRequest, opts ...grpc.CallOption) (*RemoveTagLVReply, error)
	ListVG(ctx context.Context, in *ListVGRequest, opts ...grpc.CallOption) (*ListVGReply, error)
	CreateVG(ctx context.Context, in *CreateVGRequest, opts ...grpc.CallOption) (*CreateVGReply, error)
	RemoveVG(ctx context.Context, in *CreateVGRequest, opts ...grpc.CallOption) (*RemoveVGReply, error)
	CleanPath(ctx context.Context, in *CleanPathRequest, opts ...grpc.CallOption) (*CleanPathReply, error)
	CleanDevice(ctx context.Context, in *CleanDeviceRequest, opts ...grpc.CallOption) (*CleanDeviceReply, error)
	DoCommand(ctx context.Context, in *DoCommandRequest, opts ...grpc.CallOption) (*DoCommandReply, error)
}

type lVMClient struct {
	cc grpc.ClientConnInterface
}

func NewLVMClient(cc grpc.ClientConnInterface) LVMClient {
	return &lVMClient{cc}
}

func (c *lVMClient) ListLV(ctx context.Context, in *ListLVRequest, opts ...grpc.CallOption) (*ListLVReply, error) {
	out := new(ListLVReply)
	err := c.cc.Invoke(ctx, LVM_ListLV_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) CreateLV(ctx context.Context, in *CreateLVRequest, opts ...grpc.CallOption) (*CreateLVReply, error) {
	out := new(CreateLVReply)
	err := c.cc.Invoke(ctx, LVM_CreateLV_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) RemoveLV(ctx context.Context, in *RemoveLVRequest, opts ...grpc.CallOption) (*RemoveLVReply, error) {
	out := new(RemoveLVReply)
	err := c.cc.Invoke(ctx, LVM_RemoveLV_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) CloneLV(ctx context.Context, in *CloneLVRequest, opts ...grpc.CallOption) (*CloneLVReply, error) {
	out := new(CloneLVReply)
	err := c.cc.Invoke(ctx, LVM_CloneLV_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) ExpandLV(ctx context.Context, in *ExpandLVRequest, opts ...grpc.CallOption) (*ExpandLVReply, error) {
	out := new(ExpandLVReply)
	err := c.cc.Invoke(ctx, LVM_ExpandLV_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotReply, error) {
	out := new(CreateSnapshotReply)
	err := c.cc.Invoke(ctx, LVM_CreateSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) RemoveSnapshot(ctx context.Context, in *RemoveSnapshotRequest, opts ...grpc.CallOption) (*RemoveSnapshotReply, error) {
	out := new(RemoveSnapshotReply)
	err := c.cc.Invoke(ctx, LVM_RemoveSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) AddTagLV(ctx context.Context, in *AddTagLVRequest, opts ...grpc.CallOption) (*AddTagLVReply, error) {
	out := new(AddTagLVReply)
	err := c.cc.Invoke(ctx, LVM_AddTagLV_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) RemoveTagLV(ctx context.Context, in *RemoveTagLVRequest, opts ...grpc.CallOption) (*RemoveTagLVReply, error) {
	out := new(RemoveTagLVReply)
	err := c.cc.Invoke(ctx, LVM_RemoveTagLV_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) ListVG(ctx context.Context, in *ListVGRequest, opts ...grpc.CallOption) (*ListVGReply, error) {
	out := new(ListVGReply)
	err := c.cc.Invoke(ctx, LVM_ListVG_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) CreateVG(ctx context.Context, in *CreateVGRequest, opts ...grpc.CallOption) (*CreateVGReply, error) {
	out := new(CreateVGReply)
	err := c.cc.Invoke(ctx, LVM_CreateVG_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) RemoveVG(ctx context.Context, in *CreateVGRequest, opts ...grpc.CallOption) (*RemoveVGReply, error) {
	out := new(RemoveVGReply)
	err := c.cc.Invoke(ctx, LVM_RemoveVG_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) CleanPath(ctx context.Context, in *CleanPathRequest, opts ...grpc.CallOption) (*CleanPathReply, error) {
	out := new(CleanPathReply)
	err := c.cc.Invoke(ctx, LVM_CleanPath_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) CleanDevice(ctx context.Context, in *CleanDeviceRequest, opts ...grpc.CallOption) (*CleanDeviceReply, error) {
	out := new(CleanDeviceReply)
	err := c.cc.Invoke(ctx, LVM_CleanDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) DoCommand(ctx context.Context, in *DoCommandRequest, opts ...grpc.CallOption) (*DoCommandReply, error) {
	out := new(DoCommandReply)
	err := c.cc.Invoke(ctx, LVM_DoCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LVMServer is the server API for LVM service.
// All implementations must embed UnimplementedLVMServer
// for forward compatibility
type LVMServer interface {
	ListLV(context.Context, *ListLVRequest) (*ListLVReply, error)
	CreateLV(context.Context, *CreateLVRequest) (*CreateLVReply, error)
	RemoveLV(context.Context, *RemoveLVRequest) (*RemoveLVReply, error)
	CloneLV(context.Context, *CloneLVRequest) (*CloneLVReply, error)
	ExpandLV(context.Context, *ExpandLVRequest) (*ExpandLVReply, error)
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotReply, error)
	RemoveSnapshot(context.Context, *RemoveSnapshotRequest) (*RemoveSnapshotReply, error)
	AddTagLV(context.Context, *AddTagLVRequest) (*AddTagLVReply, error)
	RemoveTagLV(context.Context, *RemoveTagLVRequest) (*RemoveTagLVReply, error)
	ListVG(context.Context, *ListVGRequest) (*ListVGReply, error)
	CreateVG(context.Context, *CreateVGRequest) (*CreateVGReply, error)
	RemoveVG(context.Context, *CreateVGRequest) (*RemoveVGReply, error)
	CleanPath(context.Context, *CleanPathRequest) (*CleanPathReply, error)
	CleanDevice(context.Context, *CleanDeviceRequest) (*CleanDeviceReply, error)
	DoCommand(context.Context, *DoCommandRequest) (*DoCommandReply, error)
	mustEmbedUnimplementedLVMServer()
}

// UnimplementedLVMServer must be embedded to have forward compatible implementations.
type UnimplementedLVMServer struct {
}

func (UnimplementedLVMServer) ListLV(context.Context, *ListLVRequest) (*ListLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLV not implemented")
}
func (UnimplementedLVMServer) CreateLV(context.Context, *CreateLVRequest) (*CreateLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLV not implemented")
}
func (UnimplementedLVMServer) RemoveLV(context.Context, *RemoveLVRequest) (*RemoveLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLV not implemented")
}
func (UnimplementedLVMServer) CloneLV(context.Context, *CloneLVRequest) (*CloneLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneLV not implemented")
}
func (UnimplementedLVMServer) ExpandLV(context.Context, *ExpandLVRequest) (*ExpandLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpandLV not implemented")
}
func (UnimplementedLVMServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedLVMServer) RemoveSnapshot(context.Context, *RemoveSnapshotRequest) (*RemoveSnapshotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSnapshot not implemented")
}
func (UnimplementedLVMServer) AddTagLV(context.Context, *AddTagLVRequest) (*AddTagLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTagLV not implemented")
}
func (UnimplementedLVMServer) RemoveTagLV(context.Context, *RemoveTagLVRequest) (*RemoveTagLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTagLV not implemented")
}
func (UnimplementedLVMServer) ListVG(context.Context, *ListVGRequest) (*ListVGReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVG not implemented")
}
func (UnimplementedLVMServer) CreateVG(context.Context, *CreateVGRequest) (*CreateVGReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVG not implemented")
}
func (UnimplementedLVMServer) RemoveVG(context.Context, *CreateVGRequest) (*RemoveVGReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveVG not implemented")
}
func (UnimplementedLVMServer) CleanPath(context.Context, *CleanPathRequest) (*CleanPathReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanPath not implemented")
}
func (UnimplementedLVMServer) CleanDevice(context.Context, *CleanDeviceRequest) (*CleanDeviceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanDevice not implemented")
}
func (UnimplementedLVMServer) DoCommand(context.Context, *DoCommandRequest) (*DoCommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoCommand not implemented")
}
func (UnimplementedLVMServer) mustEmbedUnimplementedLVMServer() {}

// UnsafeLVMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LVMServer will
// result in compilation errors.
type UnsafeLVMServer interface {
	mustEmbedUnimplementedLVMServer()
}

func RegisterLVMServer(s grpc.ServiceRegistrar, srv LVMServer) {
	s.RegisterService(&LVM_ServiceDesc, srv)
}

func _LVM_ListLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).ListLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_ListLV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).ListLV(ctx, req.(*ListLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_CreateLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).CreateLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_CreateLV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).CreateLV(ctx, req.(*CreateLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_RemoveLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).RemoveLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_RemoveLV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).RemoveLV(ctx, req.(*RemoveLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_CloneLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).CloneLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_CloneLV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).CloneLV(ctx, req.(*CloneLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_ExpandLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).ExpandLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_ExpandLV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).ExpandLV(ctx, req.(*ExpandLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_RemoveSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).RemoveSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_RemoveSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).RemoveSnapshot(ctx, req.(*RemoveSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_AddTagLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTagLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).AddTagLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_AddTagLV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).AddTagLV(ctx, req.(*AddTagLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_RemoveTagLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTagLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).RemoveTagLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_RemoveTagLV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).RemoveTagLV(ctx, req.(*RemoveTagLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_ListVG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).ListVG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_ListVG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).ListVG(ctx, req.(*ListVGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_CreateVG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).CreateVG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_CreateVG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).CreateVG(ctx, req.(*CreateVGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_RemoveVG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).RemoveVG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_RemoveVG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).RemoveVG(ctx, req.(*CreateVGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_CleanPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).CleanPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_CleanPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).CleanPath(ctx, req.(*CleanPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_CleanDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).CleanDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_CleanDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).CleanDevice(ctx, req.(*CleanDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_DoCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).DoCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LVM_DoCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).DoCommand(ctx, req.(*DoCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LVM_ServiceDesc is the grpc.ServiceDesc for LVM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LVM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LVM",
	HandlerType: (*LVMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLV",
			Handler:    _LVM_ListLV_Handler,
		},
		{
			MethodName: "CreateLV",
			Handler:    _LVM_CreateLV_Handler,
		},
		{
			MethodName: "RemoveLV",
			Handler:    _LVM_RemoveLV_Handler,
		},
		{
			MethodName: "CloneLV",
			Handler:    _LVM_CloneLV_Handler,
		},
		{
			MethodName: "ExpandLV",
			Handler:    _LVM_ExpandLV_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _LVM_CreateSnapshot_Handler,
		},
		{
			MethodName: "RemoveSnapshot",
			Handler:    _LVM_RemoveSnapshot_Handler,
		},
		{
			MethodName: "AddTagLV",
			Handler:    _LVM_AddTagLV_Handler,
		},
		{
			MethodName: "RemoveTagLV",
			Handler:    _LVM_RemoveTagLV_Handler,
		},
		{
			MethodName: "ListVG",
			Handler:    _LVM_ListVG_Handler,
		},
		{
			MethodName: "CreateVG",
			Handler:    _LVM_CreateVG_Handler,
		},
		{
			MethodName: "RemoveVG",
			Handler:    _LVM_RemoveVG_Handler,
		},
		{
			MethodName: "CleanPath",
			Handler:    _LVM_CleanPath_Handler,
		},
		{
			MethodName: "CleanDevice",
			Handler:    _LVM_CleanDevice_Handler,
		},
		{
			MethodName: "DoCommand",
			Handler:    _LVM_DoCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lvm.proto",
}
