name: Release Chart

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version of release chart'
        required: true
        default: ''
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.ref_name }}

run-name: release chart ${{ inputs.release_version }} ${{ github.ref_name }}

jobs:
  release-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get_relese_version.outputs.release_version }}
    steps:
      - name: Get Release Version
        id: get_relese_version
        run: |
          RELEASE_VERSION=${{ inputs.release_version }}
          if [ -z "$RELEASE_VERSION" ]; then
              RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          fi
          echo release_version=$RELEASE_VERSION >> $GITHUB_OUTPUT

  release-chart:
    needs: release-version
    uses: apecloud/apecloud-cd/.github/workflows/release-charts.yml@v0.1.38
    with:
      MAKE_OPS: "bump-chart-ver"
      VERSION: "${{ needs.release-version.outputs.release-version }}"
      CHART_NAME: "open-local"
      CHART_DIR: "deploy"
      APECD_REF: "v0.1.38"
    secrets: inherit
